// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJEbomWa_oh72L90BcRLPNrLpZD2E-4NM',
    appId: '1:1042537679655:android:7f96a5d00094a3e1ce7702',
    messagingSenderId: '1042537679655',
    projectId: 'bloc-photo-gallery-1746a',
    storageBucket: 'bloc-photo-gallery-1746a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQUCi-BnQh07KbMb-RX6e8t8bRvnLIYts',
    appId: '1:1042537679655:ios:87352a9041688790ce7702',
    messagingSenderId: '1042537679655',
    projectId: 'bloc-photo-gallery-1746a',
    storageBucket: 'bloc-photo-gallery-1746a.appspot.com',
    iosClientId: '1042537679655-lj7d46p27lf6bhd8l0716t7hqa83ibmp.apps.googleusercontent.com',
    iosBundleId: 'com.hwangblood.blocPhotoGallery',
  );
}
